### ISSUE TITLE
Colourblind designers

### ISSUE THREAD

**Issue by nifl** [vasilisvg/human-colours#8]
In the statement, "... it could help a colourblind designer in describing the chosen colours to the client." Do you mean to say colourblind _client_? I expect a colourblind designer would have a challenging career. 😿

**Comment by vasilisvg** [comment]
Well, they certainly do exist. I know at least two of them.

**Comment by nifl** [comment]
My assumption about colourblind designers is invalid and that's what I expect, however, it seems to be an edge case more so than colourblind clients whom may be involved in careers that aren't so bound to colour. Again, this is another assumption but describes my personal use case perfectly and what makes this project brilliant toward helping describe colour to clients, colourblind or otherwise.
